### PR TITLE
Improved: ScrollControl

### PR DESCRIPTION
**Pull request by hustbeef**
I checked it again. The issue was not due to High DPI.

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
No, if you return to the previous state, then it will not work correctly:
image

**Comment by hustbeef** [comment]
It is working. But have to click the scrollbar  again and again to update the Max value of  scrollcontrol(This is need to be fixed) .

**Comment by XusinboyBekchanov** [comment]
>It is working. But have to click the scrollbar again and again to update the Max value of scrollcontrol(This is need to be fixed) .

The previous version works well, why change something that works well?

**Comment by hustbeef** [comment]
It's have a lot of blank area in the previous version when change up to the wall size.

**Comment by XusinboyBekchanov** [comment]
>It's have a lot of blank area in the previous version when change up to the wall size.

This error has been fixed:

Fixed: ScrollControl in High DPI:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/8fd34df9e6fb284cf1817cfefa240ad7587545bb

**Comment by hustbeef** [comment]
Great, this version is the best one.

**Pull request closed without merging**
