### PR TITLE
Added: the third lib RayLib and some shared Resources files

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
These libraries have no connection with the MyFbFramework library.

**Comment by hustbeef** [comment]
The RayLib library could add a control similar to the webBrows control. The Webp library is ready to support MFF in the future.

**Comment by hustbeef** [comment]
@XusinboyBekchanov, could you please create a wrapper for raylib, which is powerful and simple for 3D and 2D drawing across multiple operating systems? That is why I am uploading the library.

**Comment by XusinboyBekchanov** [comment]
But there is no way to draw using raylib in the canvas.

**Comment by XusinboyBekchanov** [comment]
There is only one possibility:

**Comment by XusinboyBekchanov** [comment]
https://gist.github.com/ChrisDill/c2ca6a0ccf592c073a8d2aaeaa4adb7f

**Comment by hustbeef** [comment]
We can manage the input and output of raylib with MFF. Raylib only renders the image.

**Comment by XusinboyBekchanov** [comment]
Then we are waiting for new examples of raylib with MFF from you.

**Pull request merged**
