### PR TITLE
Add property HideCaption for Form

### PR DESCRIPTION
**Pull request by chunmingwang**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Your method works when HideCaption is set after HandleIsAllocated. Before this, you can only change the FStyle variable.

**Comment by XusinboyBekchanov** [comment]
I changed this:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/b12d0a49e5d66bbd76574c187e1233861960888e

**Comment by chunmingwang** [comment]
Thanks!

**Comment by hustbeef** [comment]
We need move this to control.bas because I want add this to all Control. We have one Property ShowHint of control. So It is better reaname to ShowCAPTION. 
Because if the control have image and it is need  show the  CAPTION.

**Comment by XusinboyBekchanov** [comment]
I launched it, the image is shown.

**Pull request merged**
