### PR TITLE
Add: examples of control Label

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by DavidIceBird** [comment]
1.  How to make Transparent?  I do not wanta show the backcolor of Label.
  2.
 the attached version of Label is better.  Cancas.TextWidth and Cancas.TextHeight is not workig fine. but it is OK if move the code to label.bas


[cid:38f789be-4d07-464d-8556-0a5da0e395d5]
________________________________
发件人: hustbeef ***@***.***>
发送时间: 2023年11月29日 9:12
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
抄送: Subscribed ***@***.***>
主题: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/XusinboyBekchanov/MyFbFramework/pull/141

Commit Summary

  *   ad7e1bf<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/commits/ad7e1bfa42261248b443656bf84f9ebca0a59bdb> Add: examples of control Label
  *   b3e2ff7<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/commits/b3e2ff7ed2f80d4bc042c77737878eb165d8623a> Fixed: Create Font function

File Changes

(18 files<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files>)

  *   M examples/Canvas/CanvasDraw.bas<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-cb1d5a5eb008a19d50262985d0307d69e841b3a9eb3544803f73e637fe12d50b> (14)
  *   A examples/Label/Rotate Label.bas<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-78d92f3218c801efde9f3073e0a609b4b2b7dee8af6a5985dc1bc1f6f1fdb0ad> (135)
  *   M examples/Media/AnimatePlayer.frm<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-fa19cf635e180a920575be9095fad1f6ebf06166db9ba69e2e6e5fd4795bd45c> (4)
  *   M examples/Media/AnimatePlayer.rc<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-e89689f80ede5175cdc6b5e8e5d449004cdaac9bf77e1ada116f2f86bc07aa0e> (6)
  *   A examples/Media/PlayList.txt<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-6c15ee2c194a785b3d97f01e1523fd88bb96ac32ed576558b8c8323daea27d82> (7)
  *   R examples/Resources/Circle.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-e00d0f16ee017f755e46328e3c198176e5503d1ee1561b6ac51aa7e561042e79> (0)
  *   R examples/Resources/Circle_Arrow.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-6a912e0dc0843bebf31997da95253480ab59e9fab724752b990ec0103726dc16> (0)
  *   R examples/Resources/Circle_Ball.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-e6253982499955b1bafafbc887aa1f424b1d77b36585b76d011d0c84da4ac409> (0)
  *   R examples/Resources/Circle_Blue.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-3102c634cee8dcaeff476fc9bd8cf7e3310dd606e7007d7c00dd2894b6d8aa19> (0)
  *   R examples/Resources/Circle_Gray.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-fc9b5070502c74d8ce54ad1c971863d3362ec7f5b5f507aa10f83b25b7ad31fb> (0)
  *   R examples/Resources/Circle_Green.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-fdaf600c7fa538711165a28012854202fdd325af4e3bac3537232d565e16ddce> (0)
  *   R examples/Resources/Dog.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-2cec1360eb85b4726fddf4c37d8a3253656d416f14bd567d54b1955471a2644d> (0)
  *   A examples/Resources/VisualFBEditor.ico<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-06c834a69acfe156106202922d7816e7cf5f06c00cfb9993348b9ccbfe305328> (0)
  *   R examples/Resources/Wheel.png<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-2ad167eb9ea64f7aa35ed590bafff5d0c6bf3fdfd0bc72477d76b7b57c05061d> (0)
  *   R examples/Resources/background.png<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-ba53accd26ca2052b7b6c36b2ffdea8437a8c04c4df71155002454b3b89438a5> (0)
  *   R examples/Resources/horse.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-f90489058744d41e7292902977403ac46286cc0f9b26f128cf9e8a01a3d27c38> (0)
  *   R examples/Resources/welcome2.gif<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-fe6efcf9efd6ac80793b96194572469609da7a2f19b6c991b1c88e228c18f211> (0)
  *   M mff/Font.bas<https://github.com/XusinboyBekchanov/MyFbFramework/pull/141/files#diff-12980ce7420c51b46346ddf290bf9c01cd18ab07cbe0d2f0c8d7cf51c40e73af> (2)

Patch Links:

  *   https://github.com/XusinboyBekchanov/MyFbFramework/pull/141.patch
  *   https://github.com/XusinboyBekchanov/MyFbFramework/pull/141.diff

―

**Comment by XusinboyBekchanov** [comment]
>1.  How to make Transparent?  I do not wanta show the backcolor of Label.

This is how you can make it transparent:
Added: Transparent Property to Label Control:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30

> 2.
>the attached version of Label is better.  Cancas.TextWidth and Cancas.TextHeight is not workig fine. but it is OK if move the code to label.bas

Canvas.TextWidth and Canvas.TextHeight were added for the Linux version only.

**Comment by DavidIceBird** [comment]
Thanks , You are so good.
need change "Size.Height = Sz.cY " in function CalculateSize

But  The following is code is no need. and that's why I said no need the function CalculateSize and move the code to AutoSize

Case WM_WINDOWPOSCHANGING
                        If FAutoSize Then
                              Dim Size As My.Sys.Drawing.Size
                              CalculateSize Size
                              Cast(WINDOWPOS Ptr, Message.lParam)->cx = Size.Width
                              Cast(WINDOWPOS Ptr, Message.lParam)->cy = Size.Height
                        End If

Private Sub Label.HandleIsAllocated(ByRef Sender As Control)
                  If Sender.Child Then
                        With QLabel(Sender.Child)
                              .Perform(STM_SETIMAGE, .Graphic.ImageType, CInt(.Graphic.Image))
                              '.SetAutoSize
                        End With
                  End If
            End Sub

________________________________
发件人: Xusinboy Bekchanov ***@***.***>
发送时间: 2023年11月29日 11:18
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
抄送: DavidIceBird ***@***.***>; Comment ***@***.***>
主题: Re: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)


  1.  How to make Transparent? I do not wanta show the backcolor of Label.

This is how you can make it transparent:
Added: Transparent Property to Label Control:
<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

dea5731<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

the attached version of Label is better. Cancas.TextWidth and Cancas.TextHeight is not workig fine. but it is OK if move the code to label.bas

Canvas.TextWidth and Canvas.TextHeight were added for the Linux version only.

**Comment by XusinboyBekchanov** [comment]
>need change "Size.Height = Sz.cY " in function CalculateSize

I changed the code:
https://github.com/XusinboyBekchanov/MyFbFramework/commit/41a189cb2e8063fcf13ed6a76c6461664b0f3543

>But  The following is code is no need. and that's why I said no need the function CalculateSize and move the code to AutoSize

AutoSize is installed once. And the size can always change.

**Comment by DavidIceBird** [comment]
It is the same issuew on Panel for dirty painnt and transparent , Could you please run and upgrade the "Controls\MyFbFramework\examples\Canvas\CanvasDraw.bas"

[cid:a68e8718-2098-43c5-b1ae-764744208b7e]
________________________________
发件人: Liu ZiQI ***@***.***>
发送时间: 2023年11月29日 11:54
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
主题: 回复: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)

Thanks , You are so good.
need change "Size.Height = Sz.cY " in function CalculateSize

But  The following is code is no need. and that's why I said no need the function CalculateSize and move the code to AutoSize

Case WM_WINDOWPOSCHANGING
                        If FAutoSize Then
                              Dim Size As My.Sys.Drawing.Size
                              CalculateSize Size
                              Cast(WINDOWPOS Ptr, Message.lParam)->cx = Size.Width
                              Cast(WINDOWPOS Ptr, Message.lParam)->cy = Size.Height
                        End If

Private Sub Label.HandleIsAllocated(ByRef Sender As Control)
                  If Sender.Child Then
                        With QLabel(Sender.Child)
                              .Perform(STM_SETIMAGE, .Graphic.ImageType, CInt(.Graphic.Image))
                              '.SetAutoSize
                        End With
                  End If
            End Sub

________________________________
发件人: Xusinboy Bekchanov ***@***.***>
发送时间: 2023年11月29日 11:18
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
抄送: DavidIceBird ***@***.***>; Comment ***@***.***>
主题: Re: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)


  1.  How to make Transparent? I do not wanta show the backcolor of Label.

This is how you can make it transparent:
Added: Transparent Property to Label Control:
<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

dea5731<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

the attached version of Label is better. Cancas.TextWidth and Cancas.TextHeight is not workig fine. but it is OK if move the code to label.bas

Canvas.TextWidth and Canvas.TextHeight were added for the Linux version only.

**Comment by DavidIceBird** [comment]
Add to one Label .Graphic.Bitmap.LoadFromFile(ExePath & "/../Resources/VisualFBEditor.ico")
Add the code to annother Label .Graphic.Bitmap.LoadFromFile(ExePath & "/../Resources/Wheel.png")

We can show the image  but can not show the text now inn Control Label
The label is work fine and like the one I expect for Control panel before in file CanvasDraw.bas.


________________________________
发件人: Liu ZiQI ***@***.***>
发送时间: 2023年11月29日 15:22
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
主题: Re: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)

It is the same issuew on Panel for dirty painnt and transparent , Could you please run and upgrade the "Controls\MyFbFramework\examples\Canvas\CanvasDraw.bas"

[cid:a68e8718-2098-43c5-b1ae-764744208b7e]
________________________________
发件人: Liu ZiQI ***@***.***>
发送时间: 2023年11月29日 11:54
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
主题: 回复: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)

Thanks , You are so good.
need change "Size.Height = Sz.cY " in function CalculateSize

But  The following is code is no need. and that's why I said no need the function CalculateSize and move the code to AutoSize

Case WM_WINDOWPOSCHANGING
                        If FAutoSize Then
                              Dim Size As My.Sys.Drawing.Size
                              CalculateSize Size
                              Cast(WINDOWPOS Ptr, Message.lParam)->cx = Size.Width
                              Cast(WINDOWPOS Ptr, Message.lParam)->cy = Size.Height
                        End If

Private Sub Label.HandleIsAllocated(ByRef Sender As Control)
                  If Sender.Child Then
                        With QLabel(Sender.Child)
                              .Perform(STM_SETIMAGE, .Graphic.ImageType, CInt(.Graphic.Image))
                              '.SetAutoSize
                        End With
                  End If
            End Sub

________________________________
发件人: Xusinboy Bekchanov ***@***.***>
发送时间: 2023年11月29日 11:18
收件人: XusinboyBekchanov/MyFbFramework ***@***.***>
抄送: DavidIceBird ***@***.***>; Comment ***@***.***>
主题: Re: [XusinboyBekchanov/MyFbFramework] Add: examples of control Label (PR #141)


  1.  How to make Transparent? I do not wanta show the backcolor of Label.

This is how you can make it transparent:
Added: Transparent Property to Label Control:
<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

dea5731<https://github.com/XusinboyBekchanov/MyFbFramework/commit/dea5731696e34b1e582755bf9709a89b34677c30>

the attached version of Label is better. Cancas.TextWidth and Cancas.TextHeight is not workig fine. but it is OK if move the code to label.bas

Canvas.TextWidth and Canvas.TextHeight were added for the Linux version only.

**Comment by XusinboyBekchanov** [comment]
Static control cannot show both text and image at the same time. But you can draw it yourself during WM_PAINT.

**Comment by XusinboyBekchanov** [comment]
1. The CreateDoubleBuffer method of Canvas does just that. Still prints with WM_PAINT
2. .a and .lib are the same. .a for Unix, .lib for Windows.

**Pull request merged**
