### PR TITLE
Update NoInterface.bi

### PR DESCRIPTION
**Pull request by hustbeef**

### CODE REVIEW

**Comment by XusinboyBekchanov** [comment]
Need to fix a bug:

`D:\a\MyFbFramework\MyFbFramework\mff\DebugPrint.bi(289) error 272: Local symbols can't be referenced`

**Comment by XusinboyBekchanov** [comment]
There is also an error:

```
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(63) error 42: Variable not declared, MB_ICONINFORMATION
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(64) error 42: Variable not declared, MB_ICONEXCLAMATION
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(65) error 42: Variable not declared, MB_ICONQUESTION
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(66) error 42: Variable not declared, MB_ICONERROR
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(71) error 42: Variable not declared, MB_OK
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(72) error 42: Variable not declared, MB_YESNO
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(73) error 42: Variable not declared, MB_YESNOCANCEL
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(74) error 42: Variable not declared, MB_OKCANCEL
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(76) error 42: Variable not declared, MessageBox
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(78) error 42: Variable not declared, IDABORT
/home/runner/work/MyFbFramework/MyFbFramework/mff/DebugPrint.bi(78) error 133: Too many errors, exiting
```

**Comment by hustbeef** [comment]
XusinboyBekchanov,  Can you please correct the Linux part of the code?

**Comment by XusinboyBekchanov** [comment]
>XusinboyBekchanov, Can you please correct the Linux part of the code?

I'll take a look this evening, it's a mistake to say that there is no App.

**Comment by hustbeef** [comment]
In this version, the MsgBox and InputBox functions do not work properly on Windows. However, the previous version functions correctly.

**Comment by XusinboyBekchanov** [comment]
I'll take a look

**Pull request closed without merging**
