### PR TITLE
Added: Support for XML-type setting file

### PR DESCRIPTION
**Pull request by hustbeef**
I added support for XML-type setting files. The wiki information or comments are now saved with the code. However, I believe it would be better to save them in the language setting file, similar to the property of control for multiple language support.

Example
```
<?xml version="1.0"?>
<RootConfig>
  <!--comment-->
  <BackgroundPath>board.png</BackgroundPath>

</RootConfig>
```

### CODE REVIEW

**Comment by hustbeef** [comment]
Example:

<?xml version="1.0"?>
<RootConfig>
  
  <BackgroundPath>board.png</BackgroundPath>


<TagColorString>400 200 10</TagColorString>

</RootConfig>

**Comment by XusinboyBekchanov** [comment]
I think that you need to create a separate file for it called XML. Because IniFile and XML files are different things.

**Comment by hustbeef** [comment]
Yes, it does not fully support all features of XML. But it is okay for a settings file.

**Comment by XusinboyBekchanov** [comment]
Look at the IniFile: https://en.wikipedia.org/wiki/INI_file

There is no xml there.

**Comment by XusinboyBekchanov** [comment]
We can also add a JSON file (we currently have cJSON). We will make a separate file for this.

**Comment by hustbeef** [comment]
This is a expand function to  the operating settings file.  settings file could be ini_File and XML file either.

**Comment by XusinboyBekchanov** [comment]
The settings can be either XML or INI, but the name of the type (and file) is iniFile.

**Comment by hustbeef** [comment]
The code can recognize both types, not only by file name.
`If Mid(Trim(LCase(*wData)), 1, 5) = "<?xml" Then CharStart = "<": CharEnd  = ">"`

**Pull request closed without merging**
